# Generated by Django 6.1 on 2026-08-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_meeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
