# Generated by Django 6.1 on 2026-08-17 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_alter_meeting_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="conference_record",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="recording_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ParticipantAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "participant_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "participant_resource",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("first_joined", models.DateTimeField(blank=True, null=True)),
                ("last_left", models.DateTimeField(blank=True, null=True)),
                ("total_duration", models.DurationField(blank=True, null=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="meetings.meeting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField()),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="meetings.participantattendance",
                    ),
                ),
            ],
        ),
    ]
