# Generated by Django 6.1 on 2026-08-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_meeting_conference_record_meeting_recording_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="meeting_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="participantsession",
            name="session_resource",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
