# Generated by Django 6.1 on 2026-08-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0007_meetingparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantattendance",
            name="google_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
