# Generated by Django 6.1 on 2026-08-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0008_participantattendance_google_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="actual_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="actual_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="actual_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
