# Generated by Django 6.1 on 2026-08-21 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0009_meeting_actual_duration_meeting_actual_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="actual_duration",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="actual_end_time",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="actual_start_time",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="conference_record",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="participant_email",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="recording_url",
        ),
        migrations.RemoveField(
            model_name="participantattendance",
            name="meeting",
        ),
        migrations.AlterField(
            model_name="participantsession",
            name="session_resource",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conference_record", models.CharField(max_length=255, unique=True)),
                ("space", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conferences",
                        to="meetings.meeting",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="participantattendance",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="meetings.conference",
            ),
        ),
        migrations.CreateModel(
            name="ConferenceRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recording_resource", models.CharField(max_length=255, unique=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "drive_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="meetings.conference",
                    ),
                ),
            ],
        ),
    ]
