# Generated by Django 6.1 on 2026-08-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0010_remove_meeting_actual_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantattendance",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="meetings.conference",
            ),
        ),
    ]
