# Generated by Django 6.1 on 2026-08-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0011_alter_participantattendance_conference"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="auto_record",
            field=models.BooleanField(default=False),
        ),
    ]
