# Generated by Django 6.1 on 2026-08-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0012_meeting_auto_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="space_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
